### ISSUE TITLE
Projects that rely on BOSL exceptions should say that they do

### ISSUE THREAD

**Issue by daira** [ZcashFoundation/zcash_script#36]
This is important licensing information since it affects how those projects can be forked. `zcash_script` depends on `orchard` via `zcash_primitives` and `zcash_note_encryption`: see
https://github.com/ZcashFoundation/zcash_script/blob/c9fbc441efd78593ba6a9828be45baf2d6469757/Cargo.toml#L57-L58

and https://github.com/zcash/librustzcash/issues/576.

Suggested wording is:
> Downstream code forks should note that the code in this repository depends on
> the 'orchard' crate, which is licensed under the Bootstrap Open Source License.
> A license exception is provided allowing some derived works that are linked or
> combined with the 'orchard' crate to be copied or distributed under the original
> licenses (in this case MIT / Apache 2.0), provided that the included portions of
> the 'orchard' code remain subject to BOSL.
> See https://github.com/zcash/orchard/blob/main/COPYING for details of which
> derived works can make use of this exception.

See also:
* https://forum.zcashcommunity.com/t/bosl-or-mit-orchard/41439/118
* https://github.com/zcash/zcash/issues/5931 (similar issue for zcashd)
* https://github.com/zcash/librustzcash/pull/577 (PR for librustzcash)

**Comment by oxarbitrage** [comment]
I'm proposing the following actions and would like your input on whether we should implement them now. My plan is to submit a PR with the following changes:

1. Incorporate dual license files (APACHE/MIT) into this project, aligning with what Zebra and Zcash do.

2. Update the README by adding a license section, using a wording similar to Zebra's README as a reference: [Zebra License Section](https://github.com/ZcashFoundation/zebra#license).

3. Integrate the recommended wording from @daira regarding the BOSL into the newly created license section on the README.

Your thoughts on this would be greatly appreciated!
